services:
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma
    environment:
      -  CHROMA_PERSIST_DIRECTORY=/chroma
      - ANONYMIZED_TELEMTRY=False

  mcp-server:
    build: .
    container_name: mcp-server
    command:
      ["uvicorn", "src.mcp_server.server:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    expose:
      - "8000" 
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/sse')"]
      interval: 5s
      timeout: 3s
      retries: 5 

  init:
    build: .
    container_name: init
    command: ["python", "-m", "scripts.init"]
    depends_on:
      - chroma
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: "no"

  app:
    build: .
    container_name: app
    depends_on:
      init:
        condition: service_completed_successfully
      mcp-server:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./evaluation:/app/evaluation
    env_file:
      - .env
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8080"]

volumes:
  chroma_data:
    
